### PR TITLE
Updated schema for House table

### PR DESCRIPTION
**Pull request by AsimKhan2019**
Added the relevant fields and address for the house table, and updated the db schema. Kindly please let me know if there is anything else that can be changed within this request.

### CODE REVIEW

**Comment by AsimKhan2019** [comment]
House model and schema updated

**Comment by AsimKhan2019** [comment]
@hammaazarok Can I merge this pull request, if it is complete?

**Review by hammaazarok — APPROVED** [review]
Hello @AsimKhan2019 
The milestone is completed feel free to merge the pull request.

**Comment by AsimKhan2019** [comment]
@hammaazarok Thank you for the approval

**Pull request merged**
